Nuevo post: Apuntes de Álgebra II en LibreIM
libreim/blog pull request #147
Opened 2017-02-07 12:03 UTC by libreimbot

Añade *Apuntes de Álgebra II en LibreIM* de Rodrigo Raya.

2017-02-07 12:16 UTC, mroman42 requested changes
Faltaría antes de publicar:

  1. Añadir el usuario de Github de Rodrigo como autor.
  2. Enlazar directamente a los apuntes y al pdf si es posible.
  3.  Cambiar la categoría ÁLGEBRA por Álgebra.

2017-02-08 11:24 UTC, M42 commented
¡Gracias, @DiegoAsterio! Falta que el autor esté en el config.yml del blog. Si puede revisar @fdavidcl que esté, por mi parte se puede publicar ya.

2017-02-08 11:24 UTC, mroman42 approved these changes

2017-02-08 12:31 UTC, fdavidcl commented
He ajustado un par de detalles. Yo lo veo bien y Jekyll no se queja, así que lo subo ya.

2017-02-08 12:31 UTC, merged