Script para actualizar las gemas
libreim/blog pull request #160
Opened 2020-01-31 16:45 UTC by DiegoAsterio

Subo un script para actualizar las gemas con el cual he actualizado el archivo Gemfile. Despues de correr `bundle update` y actualizar Gemfile.lock he comprobado que funciona (version de ruby 2.5.3 que especifica [github](https://pages.github.com/versions/) ). Por ultimo, aclaro como construir el blog localmente dentro de CONTRIBUTING.md y tacho la informacion que no esta actualizada.

2020-02-04 12:10 UTC, mx-psi requested changes

2020-02-04 12:10 UTC, mx-psi commented on CONTRIBUTING.md
> +~~y escribe en tu terminal~~
Más que tachar yo creo que deberíamos reescribirlo, si acaso añadiendo las instrucciones de Github para construir localmente Github Pages. Si alguien quiere ver la versión anterior, no tiene más que mirar en la historia del repo.

2020-02-04 12:10 UTC, mx-psi commented on CONTRIBUTING.md
> +La [guía de estilo](//github.com/libreim/blog/blob/sites/guia-de-estilo.md) te servirá de
¿Por qué lo has cambiado? A simple vista no veo diferencias entre ambos documentos.

2020-02-04 12:10 UTC, mx-psi commented on update_versions.rb
> +require 'net/http'
Habria que documentar qué hace el script (¿entiendo que actualiza las gemas a la última versión compatible con Github Pages?) e indicar la autoría

2020-02-04 13:37 UTC, DiegoAsterio commented
Decidí tachar aquello que no se puede seguir. Tampoco pensaba ponerme a
escribir sin saber cómo se monta el blog.

----
Lo he cambiado porque el anterior enlace no funciona (adjunto captura).

----
Vale en esta semana añado la autoría y comentarios.

El mar., 4 feb. 2020 13:10, Pablo <notifications@github.com> escribió:

> *@mx-psi* requested changes on this pull request.
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/libreim/blog/pull/160#discussion_r374631807>:
>
> > +~~Hemos tratado de ponerlo fácil, y para las tareas sistemáticas de creación de~~
>
> +~~ramas y posts tenemos un archivo `Rakefile` que las automatiza. Para usarlo~~
>
> +~~necesitarás [tener Ruby instalado](https://rvm.io/). Para crear un nuevo post, clona este repositorio~~
>
> +~~y escribe en tu terminal~~
>
>
> Más que tachar yo creo que deberíamos reescribirlo, si acaso añadiendo las
> instrucciones de Github para construir localmente Github Pages. Si alguien
> quiere ver la versión anterior, no tiene más que mirar en la historia del
> repo.
> ------------------------------
>
> In CONTRIBUTING.md
> <https://github.com/libreim/blog/pull/160#discussion_r374632242>:
>
> > -La [guía de estilo](//libreim.github.io/blog/styleguide) te servirá de
>
> +La [guía de estilo](//github.com/libreim/blog/blob/sites/guia-de-estilo.md) te servirá de
>
>
> ¿Por qué lo has cambiado? A simple vista no veo diferencias entre ambos
> documentos.
> ------------------------------
>
> In update_versions.rb
> <https://github.com/libreim/blog/pull/160#discussion_r374633430>:
>
> > @@ -0,0 +1,48 @@
>
> +require 'net/http'
>
>
> Habria que documentar qué hace el script (¿entiendo que actualiza las
> gemas a la última versión compatible con Github Pages?) e indicar la autoría
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/libreim/blog/pull/160?email_source=notifications&email_token=AD2CA7MVH6K4AJSKLTB3WJLRBFLK7A5CNFSM4KOJ7V32YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCUETJWI#pullrequestreview-352924889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD2CA7PQD77OC6CBTTVC2JDRBFLK7ANCNFSM4KOJ7V3Q>
> .
>

2020-04-11 13:16 UTC, DiegoAsterio commented
Cambios a `CONTRIBUTING.md` y al script

2020-04-13 16:32 UTC, mx-psi approved these changes
Lo veo bien, añado a @fdavidcl para que de su visto bueno!

2020-04-14 09:28 UTC, fdavidcl commented
Perfecto, muchas gracias @DiegoAsterio (y @mx-psi por las revisiones). Yo lo veo bien para mergear.

2020-04-14 09:28 UTC, fdavidcl approved these changes

2020-04-14 09:29 UTC, merged